<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    protected $fillable = [
    'user_id',
    'c_name',
    'c_kana',
    'type',
    'statues',
    'accuracy',
    'i_month',
    'plannedApply',
    'i_type',
    'i_name',
    'i_kana',
    'i_who',
    'i_relation',
    'phone',
    'mail',
    'fb',
    'messe',
    'line',
    'birthday',
    'structure',
    'job',
    'company_name',
    'progress',
    'remark',
    'actualResident',
    'contacter',
    'contacter_relation',
    'plannedSales',
    'expectedPayment',
    'bf',
    'bfDate',
    'ad',
    'adDate',
    'disBF',
    'disAD',
    'useType',
    'zipcode',
    'address',
    'mansion_name',
    'rent',
    'contractDate',
    'startDate',
    'endDate',
    'period',
    'notice',
    'renewalType',
    'renewalFee',
    'settlementDate',
    'deliveryDate',
    'mcName',
    'mcPerson',
    'mcTel',
    'mcFax',
    'acting',
    'actingPerson',
    'actingKana',
    'loan',
    'distinationName',
    'd_zipcode',
    'd_address',
    'd_mansion_name'
    ];
}
